/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author Cetecom
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        lblTitulo = new javax.swing.JLabel();
        mnbMenuPrincipal = new javax.swing.JMenuBar();
        mnuCliente = new javax.swing.JMenu();
        mniAgregarCliente = new javax.swing.JMenuItem();
        mniEditarCliente = new javax.swing.JMenuItem();
        mniEliminarCliente = new javax.swing.JMenuItem();
        mniListarCliente = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("AUTOMOVILIZA");

        mnuCliente.setText("Clientes");

        mniAgregarCliente.setText("Agregar");
        mniAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(mniAgregarCliente);

        mniEditarCliente.setText("Editar");
        mniEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEditarClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(mniEditarCliente);

        mniEliminarCliente.setText("Eliminar");
        mniEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(mniEliminarCliente);

        mniListarCliente.setText("Listar");
        mniListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(mniListarCliente);

        mnbMenuPrincipal.add(mnuCliente);

        mnuSalir.setText("Salir");

        jMenuItem1.setText("Salir del Programa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuSalir.add(jMenuItem1);

        mnbMenuPrincipal.add(mnuSalir);

        setJMenuBar(mnbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarClienteActionPerformed
        agregarCliente ac = new agregarCliente();
        ac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniAgregarClienteActionPerformed

    private void mniEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEditarClienteActionPerformed
        editarCliente ec = new editarCliente();
        ec.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEditarClienteActionPerformed

    private void mniEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarClienteActionPerformed
        eliminarCliente elc = new eliminarCliente();
        elc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEliminarClienteActionPerformed

    private void mniListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarClienteActionPerformed
        listarCliente lc = new listarCliente();
        lc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniListarClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar mnbMenuPrincipal;
    private javax.swing.JMenuItem mniAgregarCliente;
    private javax.swing.JMenuItem mniEditarCliente;
    private javax.swing.JMenuItem mniEliminarCliente;
    private javax.swing.JMenuItem mniListarCliente;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
